Workflow:
  '@WorkflowId': '{5680fc8e-23f1-ef11-be20-000d3a0adb79}'
  '@Name': SuperFam - Prepare Video DB
  '@Description': This flow will extract insights from Azure AI Video Indexer, structure them, and store them in Azure AI Search for easy retrieval by LLMs.
  JsonFileName: /modernflows/5680fc8e-23f1-ef11-be20-000d3a0adb79/SuperFam-PrepareVideoDB-5680FC8E-23F1-EF11-BE20-000D3A0ADB79.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': SuperFam - Prepare Video DB
  Descriptions:
    Description:
      '@languagecode': 1033
      '@description': This flow will extract insights from Azure AI Video Indexer, structure them, and store them in Azure AI Search for easy retrieval by LLMs.
