environmentvariabledefinition:
  '@schemaname': dev_SuperFamAISearchServiceName
  description:
    '@default': The name of your azure AI search service.
    label:
      '@description': The name of your azure AI search service.
      '@languagecode': 1033
  displayname:
    '@default': SuperFam AI Search Service Name
    label:
      '@description': SuperFam AI Search Service Name
      '@languagecode': 1033
  introducedversion: 1.0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
