environmentvariabledefinition:
  '@schemaname': dev_SuperFamVIAccountId
  description:
    '@default': The unique identifier of your video indexer account.
    label:
      '@description': The unique identifier of your video indexer account.
      '@languagecode': 1033
  displayname:
    '@default': SuperFam VI Account Id
    label:
      '@description': SuperFam VI Account Id
      '@languagecode': 1033
  introducedversion: 1.0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000005
